source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'slim-rails'
gem 'zurb-foundation'
gem 'simple_form'
gem 'inherited_resources'
gem 'stripe'
gem 'settingslogic'
gem 'devise'

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'vcr'
  gem 'webmock', '< 1.12'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'shoulda-matchers'
  gem 'database_cleaner', '1.0.0.RC1'
  gem 'mailcatcher'
end
